[package]
name = "sg"
version = "0.1.0"
edition = "2021"
description = "a simple grep implementation in rust"
repository = "https://github.com/pplmx/sg"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
